import pandas as pd
import os
from pathlib import Path


class DataLoader:
    _instance = None
    _df = None

    def __new__(cls, *args, **kwargs):
        if not cls._instance:
            cls._instance = super(DataLoader, cls).__new__(cls)
        return cls._instance

    def __init__(self, data_dir="data"):
        # Resolve to absolute path relative to this file
        if os.path.isabs(data_dir):
            self.data_dir = data_dir
        else:
            env_data_dir = os.environ.get("ZIWEI_DATA_DIR")
            if env_data_dir:
                self.data_dir = str(Path(env_data_dir).expanduser().resolve())
                return
            module_dir = os.path.dirname(os.path.abspath(__file__))
            self.data_dir = os.path.join(os.path.dirname(module_dir), data_dir)
        # Lazy load in search if not loaded

    def _load_data(self):
        if self._df is not None:
            return
            
        csv_path = os.path.join(self.data_dir, "locations.csv")
        if not os.path.exists(csv_path):
            raise FileNotFoundError(f"Location data not found at {csv_path}. Please run tools/preprocess.py first.")
            
        # Use caching logic if needed, but pandas is fast enough for 20k rows
        # We assume the file is generated by preprocess.py
        # Columns: id, city_name_en, city_name_cn, keywords, lat, lon, timezone_id
        self._df = pd.read_csv(csv_path)
        # Ensure keywords are string and lowercase
        self._df['keywords'] = self._df['keywords'].astype(str).str.lower()

    def search_location(self, query):
        """
        Search for a city by query string (Chinese, English, or Pinyin).
        Returns a list of matches (dicts).
        """
        self._load_data()
        
        q = query.strip().lower()
        if not q:
            return []
            
        # Fuzzy search in keywords
        # 1. Exact match in city_name_en or city_name_cn
        # 2. 'contains' in keywords
        
        # Priority: Exact matches first
        # But for simplicity, we just filter by 'contains' in keywords
        
        matches = self._df[self._df['keywords'].str.contains(q, na=False)]
        
        # Sort by exact match or population (if we had population).
        # We don't have population in locations.csv, so just return top results.
        # Maybe we should have kept population in preprocess.py?
        # The prompt said "Screen population > 15000", but didn't say output it.
        # It's fine.
        
        results = matches.head(10).to_dict('records')
        return results

    def get_location_by_id(self, loc_id):
        self._load_data()
        row = self._df[self._df['id'] == loc_id]
        if row.empty:
            return None
        return row.iloc[0].to_dict()
